FROM node:14-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
ARG REACT_APP_API_URL
ARG REACT_APP_ACCESS_TOKEN_MAP_BOX
ENV REACT_APP_API_URL=$REACT_APP_API_URL
ENV REACT_APP_ACCESS_TOKEN_MAP_BOX=$REACT_APP_ACCESS_TOKEN_MAP_BOX
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
